require 'spec_helper'

include Capybara::DSL
include Devise::TestHelpers#require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe UsersController do

  describe "Test user editing settings" do
      it "edit settings" do
        visit '/'
        click_link 'Sign in'
        page.should have_content "Sign in"
        fill_in "Email", :with => 'user1@gmail.com'
        fill_in "Password", :with => 'ppppp1'
        click_button "Sign in"
        page.should have_content "Signed in successfully"
        
        click_link 'Edit settings'
        page.should have_content "Editing user"
        fill_in "About", :with => 'This is some content'
        click_button "Update User"
        page.should have_content "This is some content"
      end
  end

end
